### ISSUE TITLE
OperationalError: no such column: google_id when running upload

### ISSUE THREAD

**Issue by capsudo** [gustible/googlephotos#11]
`python ./gp.py -u -v` (After having checked view files in the database):

```
Traceback (most recent call last):
  File "./gp.py", line 469, in <module>
    main()
  File "./gp.py", line 407, in main
    album_id, album_name, album_count = set_up_album(authed_session)
  File "./gp.py", line 145, in set_up_album
    album_name, album_id = get_active_album_name()
  File "./gp.py", line 94, in get_active_album_name
    c.execute('select album_name, increment, google_id from albumname')
sqlite3.OperationalError: no such column: google_id
```

Indeed field `google_id` is missing in table `albumname`

![image](https://user-images.githubusercontent.com/18724661/196145813-de5e5a12-b615-467a-a00e-6014269e01f0.png)

edit: added DB structure image from SQLite DB Browser

**Comment by capsudo** [comment]
This is due to column `google_id` not being created by `create_database_structure()`:

```python
def create_database_structure():
    """
    Sets up the database structure only if the tables do not exist
    :return: None
    """
    sql = "create table if not exists imagelist(localpath, google_id, dateuploaded)"
    connsql.execute(sql)
    sql = "create table if not exists albumname(album_name, increment)"
    connsql.execute(sql)
    sql = "create table if not exists token(token, refresh_token, token_uri, " \
          "client_id, client_secret, datesaved)"
    connsql.execute(sql)
```
