### ISSUE TITLE
OperationalError: no such table: imagelist when running check

### ISSUE THREAD

**Issue by capsudo** [gustible/googlephotos#9]
`python ./gp.py -c -i C:\some\folder\pathi -a some-album-name -v`

```
Traceback (most recent call last):
  File "./gp.py", line 468, in <module>
    main()
  File "./gp.py", line 401, in main
    check_files(args.imagedir)
  File "./gp.py", line 217, in check_files
    store_file_details(f_path)
  File "./gp.py", line 186, in store_file_details
    c.execute('select rowid from imagelist where localpath = ?;', parms)
sqlite3.OperationalError: no such table: imagelist
```

**Comment by capsudo** [comment]
This is due to `create_database_structure` being called only for `upload` command not for `check`:

```python
    if args.check:
        check_files(args.imagedir)

    if args.upload:
        create_database_structure()
        authed_session = get_authed_session()
        album_id, album_name, album_count = set_up_album(authed_session)
```

**Comment by gustible** [comment]
Thank you @xididri !
